#!/usr/bin/php
<?php

//simulate
$sim = true;
if(count($argv)>0 && in_array('--run', $argv)){
	$sim=false;
}else{
	echoLine('This is a {{SIMULATION}} please run flag {{--run}} for the real deal','yellow');
}

echoLine('Getting List of enviroments ...');
exec('eb list',$envs);
$count = count($envs);
if($count==0){
	echoLine("{{ERROR:}} Could not retrieve list of enviroments",'red');
	die();
}
if(preg_match('/^(ERROR|WARN)/',$envs[0])){
	echo implode("\n", $envs) . "\n";
	echoLine("{{Doesn't look like enviroments are set up}}",'red');
	exit;
}
echoLine("Recieved {{{$count}}} Enviroments",'green');
foreach ($envs as $i => $env) {
	$n = $i+1;
	echoLine( "\t{$n})\t{$env}");
}

foreach ($envs as $i => $env) {
	$n = $i+1;
	if($i>0){
		//not first
		echoLine("Deploying To {{#{$n}}} -> {{{$env}}}", 'green');
		if(!$sim){
			passthru("eb deploy {$env} --verbose --nohang");
		}
	}else{
		//first one
		echoLine("Deploying To {{{$env}}} for first time", 'green');
		if(!$sim){
			passthru("eb deploy {$env} --verbose");
		}

		if(count($envs)>1){
			echoLine("\nDone with {$env} will quietly deploy others");
		}
	}
	$percent = round (($n*100)/$count,2);
	echoLine("\n{{{$percent} %}} Deployed \n",'yellow');
}

echoLine('{{Nothing actually happened, see SIMULATION notice above}}','red');

function echoLine($msg, $color=false){
	if($color){
		$colors =[
			'black'			=> '0;30',
			'dark_gray'		=> '1;30',
			'blue'			=> '0;34',
			'light_blue'	=> '1;34',
			'green'			=> '0;32',
			'light_green'	=> '1;32',
			'cyan'			=> '0;36',
			'light_cyan'	=> '1;36',
			'red'			=> '0;31',
			'light_red'		=> '1;31',
			'purple'		=> '0;35',
			'light_purple'	=> '1;35',
			'brown'			=> '0;33',
			'yellow'		=> '1;33',
			'light_gray'	=> '0;37',
			'white'			=> '1;37',
		];
		$msg = preg_replace('/(\{\{)([^\}]+)(\}\})/', "\033[{$colors[$color]}m$2\033[0m", $msg);
	}
	echo $msg . "\n";
}
?>
